CREATE SCHEMA IF NOT EXISTS kanban;

CREATE TABLE IF NOT EXISTS PROJECT (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CARD (
   id INT NOT NULL AUTO_INCREMENT,
   state VARCHAR(20) NOT NULL,
   label VARCHAR(200) NOT NULL,
   prj_id INT NOT NULL,
   PRIMARY KEY ( id ),
   FOREIGN KEY ( prj_id ) REFERENCES PROJECT( id )
);