# Generated by Django 3.1.3 on 2020-11-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
